apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-secrets
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: fastapi-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/k8s-fastapi-k8s/config
        property: DATABASE_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: prod/k8s-fastapi-k8s/config
        property: SECRET_KEY
